[project]
name = "club-chatbot"
version = "1.0.0"
description = "RAG Chatbot API for the Coding Ninjas 10X Club"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "uvicorn[standard]",
    "langchain",
    "langchain-community",
    "langchain-text-splitters",
    "langchain-chroma>=1.1.0",
    "chromadb",
    "python-dotenv",
    "requests",
]
